### ISSUE TITLE
Create commit message template

### ISSUE THREAD

**Issue by chbae** [webosce/README#1]
Create commit message template and  write it in wiki page

**Comment by lsahn-gh** [comment]
## Proposal

### 1. Template for a commit of **a file**.
```
Filename without extension: Explain WHAT you did briefly

Explanation of WHY you did it. <Optional if the first line is clear>

Fix: Issue <Optional if it exists>

Signed-off-by: author <author's email>
```
For example,
```
main: Add debug toggle option

To allow users debug the app at runtime, toggle option is needed.

Fix: webosce/build-webos/issues#1

Signed-off-by: Yi-Soo An <email@email.com>
```

### 2. Template for a commit of **a feature**.
```
Explain WHAT you did briefly

Explanation of WHY you did it, but it should be in more detail.

Fix: Issue <Optional, see the first case>

Signed-off-by: author <author's email>
```
For example,
```
Add debug option

To allow users debug the app at runtime, add debug option.

include:
  main.c
  application.c
  window.c

Fix: #1

Signed-off-by: Yi-Soo An <email@email.com>
```

### For Your Information
1. The case of number 2 could include a few files in a commit.
2. ``Fix`` could be as ``repo/issues#<number>`` or just ``#<number>`` -- See https://github.com/webosce/README/issues/1#issuecomment-415934112 about it in further detail.

**Comment by chbae** [comment]
@memnoth 
Issue 번호를 달때는 https://help.github.com/articles/closing-issues-using-keywords/ 를 참고해서 전체 URL이 아닌 "fix #1" 이런식으로 달아도 괜찮을 것 같습니다.

**Comment by sukdo399** [comment]
한 가지 내용으로 여러 파일을 한번에 수정하는 경우도 있는데 그런 경우는 어떻게 하면 좋을까요

**Comment by lsahn-gh** [comment]
@sukdo399 그 경우는 2번 템플릿에 포함될 것 같아서 관련내용을 수정하였습니다.

**Comment by sukdo399** [comment]
@memnoth issue 번호는 아래와 같이 작성하면 좋을 것 같습니다. (아래 #이후 issue 번호)
Fix: webosce/README#1

*. #1 형식은 같은 repo안에서 사용
*. cross repo를 위해서는 위와 같이 webosce/README#1

wiki에도 수정 해 놓겠습니다.

**Comment by lsahn-gh** [comment]
@sukdo399 말씀해주신 한 커밋에 여러파일이 수정되는 경우는 커밋 메세지에 파일 이름을 포함하는건 어떨까요? 위에 예제를 추가해서 수정했습니다.

**Comment by sukdo399** [comment]
@memnoth 파일 이름을 다 적는 것은 commit message 자체가 복잡해 보이지 않을까요? 수십개 이상 수정하는 경우도 생각보다 많고요. 그리고 diff나 git log에도 수정한 파일 목록들은 나오기 때문에 저는 파일 이름까지는 다 적지 않아도 좋겠다고 개인적으로 생각하는데 다른 분들 의견도 한번 들어볼까요

**Comment by lsahn-gh** [comment]
@sukdo399 아 그런경우도 있을 수 있겠네요. 저도 다른 분들 의견을 들어보는것도 좋다고 생각합니다.

**Comment by chbae** [comment]
1. 컴포넌트
수정 내역만 적어도 될 것 같습니다.

2. meta layer
파일 한개는 적는게 좋을 것 같고요. 여러개면 큰 제목만 붙이면 될 것 같습니다. 그리고 컴포넌트 수정사항은 컴포넌트 이름으로 적으면 좋을 것 같고요.

**Comment by chbae** [comment]
please see https://github.com/webosce/README/wiki/Commit-Message-Template and close this issue.
