### ISSUE TITLE
Develop retroPie application (Support usb joystick)

### ISSUE THREAD

**Issue by flowergom** [webosce/README#12]
Development retroPie application
retroPie(https://retropie.org.uk/)
- RetroPie allows you to turn your Raspberry Pi, ODroid C1/C2, or PC into a retro-gaming machine. 
- It is already running on Raspbian OS.
- Enable joystick on raspberryPi

**Comment by sukdo399** [comment]
simple test.
i just added and loaded ff-memless and xpad kernel modules.
then /dev/input/eventX works fine using logitech f510 xinput mode. (direct input mode was not tested)
need to investigate from LSM to chromium.
