### ISSUE TITLE
luna service which supports gpio control.

### ISSUE THREAD

**Issue by sukdo399** [webosce/README#14]
**Is your feature request related to a problem? Please describe.**
there is no luna service which supports gpio control.

**Describe the solution you'd like**
design/implement luna service which supports gpio control.

**Comment by lsahn-gh** [comment]
If the gpio control is for the series of rpi, just add one more abstract layer on the wiringpi and then implement the service at the layer. Otherwise, it could be a challenge to implement a direct access to GPIO address for others.

Anyway I'd like to take this issue

**Comment by sukdo399** [comment]
@memnoth 
As I Know, a number of people are interested in this topic.
It would be nice to discuss about collaboration with them at the slack.

**Comment by junhoryu** [comment]
@memnoth 

I am currently working on gpio cntrl service for WebOS
if you want do this job together
pls check https://github.com/junhoryu/com.gpiotest.service.native

**Comment by lsahn-gh** [comment]
@junhoryu 

For your information

If you do not want to close the issue, commit your changes without ``Fix:``. That is a system closes an issue related to the commit automatically.
