### ISSUE TITLE
Dockerize webOS image build system for any distros.

### ISSUE THREAD

**Issue by lsahn-gh** [webosce/README#26]
**Is your feature request related to a problem? Please describe.**
Currently, webOS build system is depended on Ubuntu. To provide the build system on any distros, dockerize it.

**Describe the solution you'd like**
Developers should be able to build the webOS image with Docker on any distros.

**Comment by lsahn-gh** [comment]
Project link: https://github.com/memnoth-projects/dockerize-build-system

**Tested OS**
- Fedora 28

**Comment by chbae** [comment]
Move repository to https://github.com/webosce/dockerize-build-system
