### ISSUE TITLE
webOS OSE Capture

### ISSUE THREAD

**Issue by JunHwaPark** [webosce/README#28]
**Is your feature request related to a problem? Please describe.**
webOS OSE does not have many features yet. Window capture is one of them, and I think it will be necessary. 

**Describe the solution you'd like**
When certain keyboard events occur or when you press a button on the UI, service captures the current screen and save the image file to the specified directory.

**Comment by JunHwaPark** [comment]
Project Link : [https://github.com/JunHwaPark/webososeshutdown](https://github.com/JunHwaPark/webososeshutdown)

**Comment by chbae** [comment]
please check http://forum.webosose.org/t/capturing-screenshots-on-webos/326/5

**Comment by JunHwaPark** [comment]
Sorry, I missed it. Thank you for your comment.
