### ISSUE TITLE
enable libsdl2 components.

### ISSUE THREAD

**Issue by sukdo399** [webosce/README#9]
**Is your feature request related to a problem? Please describe.**
libsdl2 is not included in the target image.

**Describe the solution you'd like**
libsdl2 is not include in the target image because there is no component which uses it.
so please find appropriate "packagegroup" and include libsdl2 using (R)DEPENDS.
then, if necessary, we need to modify wayland porting layer of libsdl2.

**components**
- libsdl2 (mandatory)
- libsdl2-ttf
- libsdl2-mixer
- libsdl2-image

**Comment by lsahn-gh** [comment]
**webos-recipe-blacklist-world.inc** 에서 libsdl관련 파트 주석으로 만들고 meta-oe에서 meta-webosose로 libsdl 백포팅했고 libsdl 컴파일 완료, webos 이미지 빌드도 완료를 했는데 qemu로 실행시킨후에 이게 제대로 빌드되었는지 ssh에서 확인하는 방법이 있을까요?

**Comment by sukdo399** [comment]
일단은 가장 간단하게는 target에 /usr/lib에 라이브러리들이 들어가 있는지만 보면 될 것 같습니다. 아직 sdl 관련 test case나 검증 프로세스는 없기 때문에, 기본 동작 확인을 위해서는 간단한 sdl app을 만들어서 테스트해볼 수는 있겠네요. sdl의 wayland backport쪽이 잘 연결되어 있다면 (webOS의 wayland와) 간단하게 window를 만들고 mouse/keyboard event가 잘 올라오겠네요~. 간단한 테스트 용도 sdl 앱들은 몇 개 만들어 둔 것이 저에게 있습니다.

**Comment by Herrie82** [comment]
LuneOS has tests for it: https://github.com/webOS-ports/meta-webos-ports/tree/pyro/meta-luneos/recipes-graphics/sdl2-opengles-test

**Comment by sukdo399** [comment]
@Herrie82 Thank you! but source uri seems to be broken.
